### PR TITLE
feat: custom advancement system

### PR DESCRIPTION
**Pull request by mathearbeit76**
- [x] api to create advancements
- [x] api to earn advancements
- [x] advancement screen
- [x] rewards
- [x] unlocking mechanism
- [x] serialization
- [x] database (for persistent advancements)
- [x] JIT advancement compilation

### CODE REVIEW

**Comment by mathearbeit76** [comment]
state of work: you can now send a test advancement using /notify

**Comment by mathearbeit76** [comment]
todo: reaward advancements after rejoin because they are revoked

**Comment by mathearbeit76** [comment]
- [ ] rewards
- [ ] database

**Comment by mathearbeit76** [comment]
@DinoMarlir do you want to use MongoDB for this project?

**Comment by DinoMarlir** [comment]
Yeah, MongoDB with local caching. Huge thanks for your big contribution!

**Comment by mathearbeit76** [comment]
todo: advancements need to be compiled just-in-time to fix all toasts reappearing after rejoin

**Comment by mathearbeit76** [comment]
@DinoMarlir please review

**Comment by mathearbeit76** [comment]
mongodb credentials can be set with env variables (for example through docker)

**Comment by DinoMarlir** [comment]
> mongodb credentials can be set with env variables (for example through docker)

good idea!

**Review by DinoMarlir — APPROVED** [review]
Looks very good to me, thank you for your contribution!

Judging on your messages on Discord I think everything works, right?

**Comment by mathearbeit76** [comment]
Yes, that is correct.

**Pull request merged**
